# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58e6f0ad063165ac54d6be6f3031a97865f5eff14ae2d1ae805f1d0af40be39786bc069a1fa1c50e6165682a0f25b0f2d702241ee477d1d4d35b6ef642ea599f

test:
  secret_key_base: ceab37b9c67f5fbcd671a5885436ec1fe210f279f9350f26f4ec53801c043f0b56a1593798867fb96292fb440bd58fd4441d6f0ef81f05bb3b5de718b1bb58eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
